name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'

      - name: Update version in plugins
        env:
          PLUGIN_VERSION: "v${{ steps.semver_parser.outputs.fullversion }}"
        run: |
          cd cstrike/addons/amxmodx/scripting/include
          sed -i "s|%CA_VERSION%|$PLUGIN_VERSION|g" ChatAdditions.inc

          echo "asset_plugin_name=ChatAdditions-$PLUGIN_VERSION" >> $GITHUB_ENV

      - name: Build project
        run: |
          zip -r my-artifact cstrike

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./my-artifact.zip
          asset_name: ${{ env.asset_plugin_name }}.zip
          asset_content_type: application/zip
